[autolabel."wontfix"]
trigger_labels = [
  "bug"
]

[assign]
users_on_vacation = ["octocat"]

[autolabel."invalid"]
new_issue = true

[autolabel."documentation"]
new_pr = true

[autolabel."help wanted"]
new_pr = true
new_issue = true
exclude_labels = ["duplicate"]
